### ISSUE TITLE
q issue opens old repository

### ISSUE THREAD

**Issue by srobroek** [aws/amazon-q-developer-cli#137]
Checks
I ran q doctor in the affected command line session and it didn't resolve my issue *
I ran q restart and it didn't resolve my issue *
I searched and there are no duplicates of my issue *

Expected behaviour:
after running `q issue`, the new repository issue page should be opened.

Actual behaviour:

https://github.com/aws/q-command-line-discussions is opened instead

Steps to reproduce:

run `q issue` and enter any issue title

Environment

[q-details]
version = "1.5.0"
hash = "b724dbb5086098abbea6304684a779508e864e24"
date = "2024-11-21T17:26:56.475228Z (6d ago)"
variant = "full"

[system-info]
os = "macOS 15.1.1 (24B91)"
chip = "Apple M1 Pro"
total-cores = 8
memory = "32.00 GB"

[environment]
cwd = "/"
cli-path = "/"
os = "Mac"
shell-path = "/opt/homebrew/Cellar/fish/3.7.1/bin/fish"
shell-version = "3.7.1"
terminal = "iTerm 2"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.local/share/mise/installs/go/1.23.0/bin:/Users/USER/.local/share/mise/installs/go/1.23.0/go/bin:/Users/USER/.local/share/mise/installs/python/latest/bin:/Users/USER/.local/share/mise/installs/terraform-ls/latest/bin:/Users/USER/.local/share/mise/installs/kustomize/latest/bin:/Users/USER/.local/share/mise/installs/helm/latest/bin:/Users/USER/.local/share/mise/installs/flux2/latest/bin:/Users/USER/.local/share/mise/installs/k6/latest/bin:/Users/USER/.local/share/mise/installs/devspace/latest/bin:/Users/USER/.local/share/mise/installs/awscli/latest/bin:/Users/USER/.local/share/mise/installs/node/latest/bin:/Users/USER/.local/share/mise/installs/redo/latest/bin:/Users/USER/.local/share/mise/installs/kompose/latest/bin:/Users/USER/.local/share/mise/installs/checkov/latest/bin:/Users/USER/.local/share/mise/installs/bombardier/latest/bin:/Users/USER/.local/share/mise/installs/colima/latest/bin:/Users/USER/.local/share/mise/installs/awsweeper/latest/bin:/Users/USER/.local/share/mise/installs/atlas/latest/bin:/Users/USER/.local/share/mise/installs/yq/latest/bin:/Users/USER/.local/share/mise/installs/markdownlint-cli2/latest/bin:/Users/USER/.local/share/mise/installs/kubectl/latest/bin:/Users/USER/.local/share/mise/installs/jq/latest/bin:/Users/USER/.local/share/mise/installs/chezmoi/latest/bin:/Users/USER/.local/share/mise/installs/air/latest/bin:/Users/USER/.local/share/mise/installs/terraform/latest/bin:/Users/USER/.local/share/mise/installs/kubectx/latest/bin:/Users/USER/.local/share/mise/installs/jqp/latest/bin:/Users/USER/.local/share/mise/installs/goreleaser/latest/bin:/Users/USER/.local/share/mise/installs/cheat/latest/bin:/Users/USER/.local/share/mise/installs/bat/latest/bin:/Users/USER/.local/share/mise/installs/bun/latest/bin:/Users/USER/.local/share/mise/installs/1password-cli/latest/bin:/Users/USER/.local/share/mise/installs/aws-sam-cli/latest/bin:/Users/USER/.local/share/mise/installs/task/latest/bin:/Users/USER/Library/pnpm:/Users/USER/.toolbox/bin:/Users/USER/.sst/bin:/usr/local/sbin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USER/.local/bin"
QTERM_SESSION_ID = "c8c11d9a40644c51bf6330c48872ceb5"
Q_PARENT = ""
Q_TERM = "1.5.0"
SHELL = "/opt/homebrew/bin/fish"
TERM = "xterm-256color"
__CFBundleIdentifier = "com.googlecode.iterm2"

**Comment by grant0417** [comment]
This will be fixed by #139 which will be released in 1.6.0
