### ISSUE TITLE
Can't pipe text selection from helix editor into `q chat`

### ISSUE THREAD

**Issue by Rahel-A** [aws/amazon-q-developer-cli#258]
### Checks

- [X] I have searched [github.com/aws/amazon-q-developer-cli/issues](https://github.com/aws/amazon-q-developer-cli/issues?q=) and there are no duplicates of my issue
- [X] I have run `q doctor` in the affected terminal session
- [X] I have run `q restart` and replicated the issue again

### Operating system

Ubuntu 22.04 (Amazon image)

### Expected behaviour

I can pipe some text into `q chat` through the CLI (`echo "say hi"|q chat`), but I can't do the same through the helix editor.
See this for how `smartcat` works:
https://github.com/efugier/smartcat/blob/main/assets/qatohtml.gif

### Actual behaviour

For this text selection: "say hi", no output text gets saved into where the selection was.

### Steps to reproduce

Open a new buffer in helix editor.
Type "say hi"
Select text "say hi" and then press ":" to enter command mode.
Type "pipe q chat", the editor freezes for a few seconds, and "say hi" prompt disappears.

**Comment by grant0417** [comment]
The PR has been merged, thanks for the contribution.
