### ISSUE TITLE
Amazon q setting popup window is blank

### ISSUE THREAD

**Issue by rootscript** [aws/amazon-q-developer-cli#324]
### Checks

- [X] I have searched [github.com/aws/amazon-q-developer-cli/issues](https://github.com/aws/amazon-q-developer-cli/issues?q=) and there are no duplicates of my issue
- [X] I have run `q doctor` in the affected terminal session
- [X] I have run `q restart` and replicated the issue again

### Operating system

macOS 10.14.6 (18G9323)

### Expected behaviour

opening settings panel would show Amazon q preferences and settings

### Actual behaviour

Settings window was blank
![Screenshot 2024-12-26 at 21 42 22](https://github.com/user-attachments/assets/49564291-aaaf-4466-a91c-22d9c0f98d47)

### Steps to reproduce

running 'q' in iterm2 Build 3.5.0beta4
or opening settings from Amazon q menubar in MacOs
Settings window opens blank

### Environment

```yaml
[q-details]
version = "1.5.1"
hash = "43f92e418e96c7beaa3e881f299241c15ba65900"
date = "2024-12-13T00:53:22.005531Z (14d ago)"
variant = "full"

[system-info]
os = "macOS 10.14.6 (18G9323)"
chip = "Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz"
total-cores = 2
memory = "16.00 GB"

[environment]
cwd = "/"
cli-path = "/"
os = "Mac"
shell-path = "/bin/zsh"
shell-version = "5.3"
terminal = "iTerm 2"
install-method = "brew"

[env-vars]
DISPLAY = "/private/tmp/com.apple.launchd.1w4AdjO2VF/org.macosforge.xquartz:0"
PATH = "/opt/gaffer-0.54.1.0-osx/bin:/Users/USER/anaconda3/bin:/usr/local/Cellar/z/1.9/bin:/opt/local/bin:/opt/local/sbin:/Users/USER/anaconda3/bin:/usr/local/opt/ruby/bin:/Users/USER/.local/bin:/usr/local/bin:/Users/USER/.nvm/versions/node/v14.21.3/bin:/Users/USER/.nvm/versions/node/v14.21.3/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/USER/.node/bin:/Users/USER/webOS_TV_SDK/CLI/bin:/Users/USER/.local/bin:/Users/USER/webOS_TV_SDK/CLI/bin"
QTERM_SESSION_ID = "ab76f3a051164c4db24dbfd2d278b7d7"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.1"
SHELL = "/bin/zsh"
TERM = "xterm-256color"
```

**Comment by grant0417** [comment]
We do not support macOS 10.14, I would recommend you update to macOS version 11.0 onwards.
