### ISSUE TITLE
GHOSTTY TERMINAL SUPPORT

### ISSUE THREAD

**Issue by fvnju** [aws/amazon-q-developer-cli#328]
### Checks

- [X] I have searched [github.com/aws/amazon-q-developer-cli/issues](https://github.com/aws/amazon-q-developer-cli/issues?q=) and there are no duplicates of my issue
- [X] I have run `q doctor` in the affected terminal session
- [X] I have run `q restart` and replicated the issue again

### Operating system

macOS 14.5.0 (23F79)

### Expected behaviour

I expect auto-complete options

### Actual behaviour

NO AUTO-COMPLETE FUNCTIONS

### Steps to reproduce

Go to this website https://ghostty.org/download and download Ghostty.
The repo is at https://github.com/ghostty-org/ghostty

### Environment

```yaml
[q-details]
version = "1.5.1"
hash = "43f92e418e96c7beaa3e881f299241c15ba65900"
date = "2024-12-13T00:53:22.005531Z (15d ago)"
variant = "full"

[system-info]
os = "macOS 14.5.0 (23F79)"
chip = "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz"
total-cores = 6
memory = "16.00 GB"

[environment]
cwd = "/Users/USER"
cli-path = "/Users/USER"
os = "Mac"
shell-path = "/bin/zsh"
shell-version = "5.9"
install-method = "unknown"

[env-vars]
PATH = "/Users/USER/.pyenv/bin:/Users/USER/.pyenv/shims:/usr/local/bin:/Users/USER/.nvm/versions/node/v20.15.0/bin:/Users/USER/.bun/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Ghostty.app/Contents/MacOS:/Users/USER/.local/bin"
QTERM_SESSION_ID = "a6d310cff4814e57b6099fb1bc633264"
Q_SET_PARENT_CHECK = "1"
Q_TERM = "1.5.1"
SHELL = "/bin/zsh"
TERM = "xterm-ghostty"
__CFBundleIdentifier = "com.mitchellh.ghostty"
```

**Comment by vikingnope** [comment]
https://github.com/aws/amazon-q-developer-cli/issues/323

Close this as there is already another issue for this

**Comment by grant0417** [comment]
Closing this in favor of #323

**Comment by grant0417** [comment]
The 1.6.0 release of Amazon Q has been released with support for Ghostty
